const Route = {
  TEST_SCREEN: 'TEST_SCREEN',

  // PreLogin level
  LANDING_SCREEN: 'LANDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',

  FIND_BUS_SCREEN: 'FIND_BUS_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  FAVOURITE_SCREEN: 'FAVOURITE_SCREEN',

  // Root Level
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  PDF_MODAL: 'PDF_MODAL',
  WEBVIEW_MODAL: 'WEBVIEW_MODAL',
  ALERT_SCREEN: 'ALERT_SCREEN',
  HTML_CODE_VIEW_MODAL: 'HTML_CODE_VIEW_MODAL',
  ONBOARDING_TUTORIAL_SCREEN: 'ONBOARDING_TUTORIAL_SCREEN',
  SPECIAL_ANNOUNCEMENT_MODAL: 'SPECIAL_ANNOUNCEMENT_MODAL',
  BOTTOM_SHEET_SELECTION_MODAL: 'BOTTOM_SHEET_SELECTION_MODAL',

  // Popup/Overlay at the Root level
  ERROR_ALERT_MODAL: 'ERROR_ALERT_MODAL',

  TAB_STACK: 'TAB_STACK',
  MAIN_STACK: 'MAIN_STACK',
};

export default Route;
