{
  "formatVersion": "1.1",
  "component": {
    "group": "no.promon.shield",
    "module": "ShieldSDK-common",
    "version": "4.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cpl34ldvubd2jdqsvgoeoy4loe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShieldSDK-common-4.2.6.aar",
          "url": "ShieldSDK-common-4.2.6.aar",
          "size": 1758,
          "sha512": "faa970d372d88d997155c6bef741e83c1a499487bca62ec6c57f60aaadb1eef7ea67af0602b090682854c7f727ecd0be2487790ef6b558dc3dc03ad43d4b9270",
          "sha256": "1f0fe6797e1d17ea97f04ee0f0ec4f7cc3247cb6ace2ee019d8224bfab1f8273",
          "sha1": "7425d5eb4c1ea31decccb31f9630b969582fa6a1",
          "md5": "ce384c6b71f51ada7413a10058055957"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ShieldSDK-common-4.2.6.aar",
          "url": "ShieldSDK-common-4.2.6.aar",
          "size": 1758,
          "sha512": "faa970d372d88d997155c6bef741e83c1a499487bca62ec6c57f60aaadb1eef7ea67af0602b090682854c7f727ecd0be2487790ef6b558dc3dc03ad43d4b9270",
          "sha256": "1f0fe6797e1d17ea97f04ee0f0ec4f7cc3247cb6ace2ee019d8224bfab1f8273",
          "sha1": "7425d5eb4c1ea31decccb31f9630b969582fa6a1",
          "md5": "ce384c6b71f51ada7413a10058055957"
        }
      ]
    }
  ]
}
