{
  "formatVersion": "1.1",
  "component": {
    "group": "no.promon.shield",
    "module": "ShieldSDK-secure-edit-text",
    "version": "4.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cpl34ldvubd2jdqsvgoeoy4loe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "no.promon.shield",
          "module": "ShieldSDK-common",
          "version": {
            "requires": "4.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ShieldSDK-secure-edit-text-4.2.6.aar",
          "url": "ShieldSDK-secure-edit-text-4.2.6.aar",
          "size": 43162,
          "sha512": "822464fb279037154e91d712207dfa90d954f9099f803896e536c438f281060748556d7a037c84ee784fedd18c3c7fc33b6d1a88b5380a2f86b5551fb3809a78",
          "sha256": "5c882451798ec7d79f609755b29f5e00996fcf727f0788a7656a6e86283753ba",
          "sha1": "b1515ee6f7f21c125d48bd3527c718243cc04277",
          "md5": "7610dd5271d4b435619cf53348119b69"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ShieldSDK-secure-edit-text-4.2.6.aar",
          "url": "ShieldSDK-secure-edit-text-4.2.6.aar",
          "size": 43162,
          "sha512": "822464fb279037154e91d712207dfa90d954f9099f803896e536c438f281060748556d7a037c84ee784fedd18c3c7fc33b6d1a88b5380a2f86b5551fb3809a78",
          "sha256": "5c882451798ec7d79f609755b29f5e00996fcf727f0788a7656a6e86283753ba",
          "sha1": "b1515ee6f7f21c125d48bd3527c718243cc04277",
          "md5": "7610dd5271d4b435619cf53348119b69"
        }
      ]
    }
  ]
}
