{
  "formatVersion": "1.1",
  "component": {
    "group": "no.promon.shield",
    "module": "ShieldSDK-activity-guard",
    "version": "4.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cpl34ldvubd2jdqsvgoeoy4loe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "no.promon.shield",
          "module": "ShieldSDK-common",
          "version": {
            "requires": "4.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ShieldSDK-activity-guard-4.2.6.aar",
          "url": "ShieldSDK-activity-guard-4.2.6.aar",
          "size": 2683,
          "sha512": "6e3d23192d47171987758c2be902def8715e5913b918fd503cf974fefde2a21247073080c2a53bbfeb78e1e74a9ca2025af39b4dccced24d7e8e41f291096b7e",
          "sha256": "659745d04eae3c980c1accc9513567f4951099128f72f7edb3e4985490cd9d48",
          "sha1": "cd92f56a50d366b8f57e16c741d475eeb7e8f546",
          "md5": "1a15acda4417585cd78c5d5ba5fbbe6b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ShieldSDK-activity-guard-4.2.6.aar",
          "url": "ShieldSDK-activity-guard-4.2.6.aar",
          "size": 2683,
          "sha512": "6e3d23192d47171987758c2be902def8715e5913b918fd503cf974fefde2a21247073080c2a53bbfeb78e1e74a9ca2025af39b4dccced24d7e8e41f291096b7e",
          "sha256": "659745d04eae3c980c1accc9513567f4951099128f72f7edb3e4985490cd9d48",
          "sha1": "cd92f56a50d366b8f57e16c741d475eeb7e8f546",
          "md5": "1a15acda4417585cd78c5d5ba5fbbe6b"
        }
      ]
    }
  ]
}
