{
  "formatVersion": "1.1",
  "component": {
    "group": "no.promon.shield",
    "module": "ShieldSDK-secure-app-rom",
    "version": "4.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cpl34ldvubd2jdqsvgoeoy4loe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "no.promon.shield",
          "module": "ShieldSDK-common",
          "version": {
            "requires": "4.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ShieldSDK-secure-app-rom-4.2.6.aar",
          "url": "ShieldSDK-secure-app-rom-4.2.6.aar",
          "size": 4106,
          "sha512": "a486133916095c7d56db1f728be1cb4a12036d171734879d1361f4665bac9f0bf924e3bdf2784d0caca80deae204fd4525a32bcaf9474f93cb4a287ffc177b72",
          "sha256": "153678008287da9cb9a7deca35622c715ddb6d85e2a54cc455757f992608eb4d",
          "sha1": "18dfa9a0fc4653f52f2bd4bbdaf47b331805ee55",
          "md5": "4b431880d1c19b4c7d1777041c261e06"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ShieldSDK-secure-app-rom-4.2.6.aar",
          "url": "ShieldSDK-secure-app-rom-4.2.6.aar",
          "size": 4106,
          "sha512": "a486133916095c7d56db1f728be1cb4a12036d171734879d1361f4665bac9f0bf924e3bdf2784d0caca80deae204fd4525a32bcaf9474f93cb4a287ffc177b72",
          "sha256": "153678008287da9cb9a7deca35622c715ddb6d85e2a54cc455757f992608eb4d",
          "sha1": "18dfa9a0fc4653f52f2bd4bbdaf47b331805ee55",
          "md5": "4b431880d1c19b4c7d1777041c261e06"
        }
      ]
    }
  ]
}
